package traveltrack.repository;

import traveltrack.models.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    // ── Queries automatically generated by Spring Data ───────────────────
    List<User> findById(Long id);
    List<User> findByUuid(String uuid);
    List<User> findByUsername(String username);
    List<User> findByFirstname(String firstname);
    List<User> findByLastname(String lastname);
    List<User> findByEmail(String email);
    List<User> findByPhoneNumber(String phoneNumber);
    List<User> findByPassword(String password);
    List<User> findByCountry(String country);
    List<User> findByNeighbourhood(String neighbourhood);

}